{"name": "test_get_approve_tx", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \n{\"ok\":false,\"data\":null,\"error\":\"Network undefined is not available in DeBridge\"}.", "trace": "def test_get_approve_tx():  # error\":\"Network undefined is not available in DeBridge\"\n>       DeBridge().get_approve_tx()\n\ntests/api_tests/tests_de_bridge.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <serviceCalls.debrdige_service.DeBridge object at 0x10ead9820>\n\n    def get_approve_tx(self):\n        response = requests.get(f\"{self.url}getApproveTx\")\n        logger.info(f\"Отправлен запрос на роут - {response.url}\")\n        logger.info(response.text)\n>       assert response.status_code == 200, f\"Ожидался status = {200}, \" \\\n                                            f\"пришел status = {response.status_code}. \" \\\n                                            f\"Тело ответа: \\n{response.text}.\"\nE       AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \nE       {\"ok\":false,\"data\":null,\"error\":\"Network undefined is not available in DeBridge\"}.\n\nserviceCalls/debrdige_service.py:91: AssertionError"}, "attachments": [{"name": "log", "source": "ca6dbd37-85d0-4cc9-aa83-f2ab336bc7bc-attachment.txt", "type": "text/plain"}], "start": 1685610405398, "stop": 1685610405787, "uuid": "c528eda9-0887-4bdc-be37-a9504892ccdb", "historyId": "ee0cca6329720a9025f29715b4e5493c", "testCaseId": "ee0cca6329720a9025f29715b4e5493c", "fullName": "tests.api_tests.tests_de_bridge#test_get_approve_tx", "labels": [{"name": "parentSuite", "value": "tests.api_tests"}, {"name": "suite", "value": "tests_de_bridge"}, {"name": "host", "value": "MacBook-Air-Anna.local"}, {"name": "thread", "value": "16727-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api_tests.tests_de_bridge"}]}