{
  "uid" : "1c43990a32a7e631",
  "name" : "test_get_approve_tx",
  "fullName" : "tests.api_tests.tests_de_bridge#test_get_approve_tx",
  "historyId" : "ee0cca6329720a9025f29715b4e5493c",
  "time" : {
    "start" : 1685610405398,
    "stop" : 1685610405787,
    "duration" : 389
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \n{\"ok\":false,\"data\":null,\"error\":\"Network undefined is not available in DeBridge\"}.",
  "statusTrace" : "def test_get_approve_tx():  # error\":\"Network undefined is not available in DeBridge\"\n>       DeBridge().get_approve_tx()\n\ntests/api_tests/tests_de_bridge.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <serviceCalls.debrdige_service.DeBridge object at 0x10ead9820>\n\n    def get_approve_tx(self):\n        response = requests.get(f\"{self.url}getApproveTx\")\n        logger.info(f\"Отправлен запрос на роут - {response.url}\")\n        logger.info(response.text)\n>       assert response.status_code == 200, f\"Ожидался status = {200}, \" \\\n                                            f\"пришел status = {response.status_code}. \" \\\n                                            f\"Тело ответа: \\n{response.text}.\"\nE       AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \nE       {\"ok\":false,\"data\":null,\"error\":\"Network undefined is not available in DeBridge\"}.\n\nserviceCalls/debrdige_service.py:91: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \n{\"ok\":false,\"data\":null,\"error\":\"Network undefined is not available in DeBridge\"}.",
    "statusTrace" : "def test_get_approve_tx():  # error\":\"Network undefined is not available in DeBridge\"\n>       DeBridge().get_approve_tx()\n\ntests/api_tests/tests_de_bridge.py:53: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <serviceCalls.debrdige_service.DeBridge object at 0x10ead9820>\n\n    def get_approve_tx(self):\n        response = requests.get(f\"{self.url}getApproveTx\")\n        logger.info(f\"Отправлен запрос на роут - {response.url}\")\n        logger.info(response.text)\n>       assert response.status_code == 200, f\"Ожидался status = {200}, \" \\\n                                            f\"пришел status = {response.status_code}. \" \\\n                                            f\"Тело ответа: \\n{response.text}.\"\nE       AssertionError: Ожидался status = 200, пришел status = 400. Тело ответа: \nE       {\"ok\":false,\"data\":null,\"error\":\"Network undefined is not available in DeBridge\"}.\n\nserviceCalls/debrdige_service.py:91: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "92bf5b815c3ff371",
      "name" : "log",
      "source" : "92bf5b815c3ff371.txt",
      "type" : "text/plain",
      "size" : 235
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "tests.api_tests"
  }, {
    "name" : "suite",
    "value" : "tests_de_bridge"
  }, {
    "name" : "host",
    "value" : "MacBook-Air-Anna.local"
  }, {
    "name" : "thread",
    "value" : "16727-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.api_tests.tests_de_bridge"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "1c43990a32a7e631.json",
  "parameterValues" : [ ]
}